name: Build and deploy ASP.Net Core app to Azure Web App - myDotNetdhaapps

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o myapp  # Publishing directly to a folder named 'myapp'

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: myapp  # Adjust the path to the output directory of dotnet publish

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Deploy to Azure Web App using Publish Profile
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'myDotNetdhaapps'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .net-app  # This should be the directory where the artifact is unpacked
          slot-name: production
